### ISSUE TITLE
[회고] 0706 3차 웹 프로젝트 회고

### ISSUE THREAD

**Issue by blcklamb** [elice-AI4/sonsaengnim#1]
KPT 방식으로 회고를 진행합니다.

**Comment by bedurgi999** [comment]
K
- 스크럼을 통한 과정 공유
- git branch 관리 방법

**Comment by Hyes-y** [comment]
# K 
Keep(만족하고 있는 부분, 계속 이어나갔으면 하는 부분)

- 오류 및 진행상황에 대한 꼼꼼한 기록(👍)
- 팀원들의 높은 참여도(👍)
- 프로젝트의 명확한 타겟층(👍)

**Comment by elizabethgim** [comment]
Keep
- 깃랩 알림 디코에 오는 거
- 이슈에 오류 공유하는 거
- 스크럼 시간에 간단하게 공유하는 거(스크럼 시간이 효율적으로 돌아간 거)
- 누구도 낙오되지 않고, 잠수타지 않고, 열심히 한 거 
- git convetion
- 팀워크: 오프라인 모임👍

**Comment by PracticeEveryday** [comment]
K
 - google docs를 활용해 실시간으로 작성이 가능 한 점.
 - git commit message 통일
 - 배려심 깊은 사람들 😁

**Comment by Malza0408** [comment]
[K]
- 문서화 작업. 현재 내가 작업하는 과정의 가이드라인이 되기도 하고, 나중에 기억이 나지 않으면 바로바로 참고 가능하다.
- 이슈 공유. 이슈 공유가 굉장히 활발하다.
- 성실한 참여도.
- 우리가 서비스 하려는 사이트의 이해도.

**Comment by blcklamb** [comment]
K
1. 서비스 개발

1-1) 사용자에 대한 고민
웹 서비스 타겟팅에 대해 고민하고 UI를 적용하는 것이 탁월
이 부분은 코치님들에게도 긍정적인 피드백을 받았던 부분임

1-2) 저작권 의식
필요한 소스들을 직접 촬영/편집하고,
직접 그리지 않은 소스들에도 저작권 표시를 했다는 점에서 저작권에 신경쓴 것

2. 협업

- 성실한 참여
스크럼에 지각/불참하는 팀원이 거의 없었다

3. 개인

- 문서화 README.md, 이슈 작성으로 코치님들과 공유가 원활

**Comment by Malza0408** [comment]
[P]
- 현재 캠이 없는 환경에서 돌아가지 않는 서비스가 되었다. 놓친 부분이므로 개선이 필요하다.
- 반응형 웹이 아니라면 아예 반응형 웹을 꺼버리거나 최소화 시켜야 한다. 현재 반응형으로 제작된 곳이 있어서
UI가 망가지는 부분이 있다. 개선이 필요하다.
- 저작권 표시를 좀 더 예쁘게 할 방법이 있을까?

**Comment by bedurgi999** [comment]
P
- 프론트엔드 코드를 좀 더 분리시켜서 개발 했으면 좋았을 것 같다.

**Comment by Hyes-y** [comment]
# P
problem - 불편을 느꼈던 부분, 개선이 필요한 부분, 잠재적인 문제

- 세 파트 다 이전에 배우거나 사용하지 않았던 새로운 기술을 사용해보았기 때문에 추후 코드 관리 혹은 리팩토링을 위해서 관련 기술을 계속 공부하시면 좋을 것 같습니다.
- (개인) 관련 CS지식이 부족해 좀더 효율적인 구조로 프로젝트를 설계하지 못한 점이 아쉽습니다.
- (당부) 무엇보다 건강이 중요합니다 😉 먹고 살자고 하는 일! 건강 챙기세요 ❤

**Comment by elizabethgim** [comment]
Problem
- 점수판 동점자 처리 시간에 대한 것도 추가하는 게 필요할 듯 함.
- 점수판 동명이인에 대한 처리를 시각적으로 표현하는 것도 좋을 것 같음.

- 사용자가 많아지면 웹사이트가 감당할 수 있을까? 하는 고민이 있음.
- 웹사이트의 인식이 잘 안 되는 경우, ex. 최종발표 때 A가 잘 안 된다고 했음.
- 카메라가 없는 사람은 어떻게 웹사이트를 사용할지 고민해보아야 할 듯함.
- 밤새기 금지🐼🧛‍♀️🛌

**Comment by blcklamb** [comment]
## P

1. 서비스 개발

1-1) 학습 내용 증가 시 문제

현재 26개의 알파벳+21개의 단어밖에 없는데 추가적으로 학습 내용을 추가할 때

별도의 모델 학습 시 필요하다


1-2) 디자인 통일성

직접 그린 것과 freepik에서 따온 것이 혼재되어 통일되지 않은 감이 있음

2. 협업

- 타 포지션 이슈 확인

3. 개인

3-1) 컨디션 관리

프로젝트 중에도 컨디션을 유지해가면서 진행해야 끝까지 무사히 갈 수 있었을텐데 4주차 쯤 무너졌음


3-2) 환경 설정

mac에서 ml 코드들이 잘 돌아가지 않았던 것이 아쉬움

환경 설정은 코치님의 도움을 받고 나서야 해결이 됐는데, 처음부터 여쭤봤으면 더 좋았을 것 같음

**Comment by PracticeEveryday** [comment]
P

 - 타 포지션의 진행도 공유
 
BE
 - Type Interface 적용 고도화
 - 각 module 유효성 검사
 - TypeScript OOP 이해도 부족

**Comment by bedurgi999** [comment]
T
- 1주일에 한 번은 코드를 정리하는 시간이 있으면 좋을 것 같습니다.
  - 공통으로 사용되는 컴포넌트를 따로 파일로 만들어 가져다 쓰기
  - 공통된 state는 custom hook이나 전역상태관리 기능을 사용
  - 공통으로 사용되는 interface 속성 옵션 설정 의논하기

**Comment by blcklamb** [comment]
T

- 포지션 간 진행 상황 공유를 위해 타 포지션, 팀원이 오류 및 진행상황에 대해서 꼼꼼히 작성을 했다면, 해당 이슈를 읽었는지 확인하는 반응/댓글을 남기자.

- 공식 프로젝트 기간 이후에도 이틀에 한 번이라도 정기적으로 스크럼을 진행하여 개선하는 과정을 이어나가자.

- 이전 프로젝트에서 새롭게 배운 라이브러리 지식, 환경설정 지식을 이슈로 공유하여 더욱 깊은 이해를 해보자.

**Comment by elizabethgim** [comment]
Try
- 스크럼 시간에 2-3분 내외로 자기 할 거 공유하기 및 스프레드 시트에 적기
- 스크럼 시간 후에 이슈 등록하면서 다른 포지션 이슈 구경하기(2분 정도 슥 훑어보기)
- 최소한 12시에 컴퓨터 끄기
- 오류 상황 발생할 때마다 이슈 등록하기, 해결방안은 어린이한테 설명한다는 생각으로 상세하게 적자...
- 문서화 작업 생활화하기, 하루 코드를 마무리하고 10분동안 작성하기

**Comment by Hyes-y** [comment]
# T
Try - 추가적인 아이디어 / problem에 관한 해결책 제시

- 캠이 없는 환경에서의 서비스 => 기존 학습 화면에서 webcam 컴포넌트를 빼거나 화면 비율(지금은 5대5?)을 다르게 하면 좋을 것 같습니다.
- 다른 포지션의 진행 상황 확인 => 프론트엔드와 인공지능은 비교적 눈에 보이는 결과물이 있었지만 백엔드는 보이는 게 없어서 공유가 안되었다고 느낄 수 있을 듯합니다 😀 백엔드도 postman 등을 이용하여 최대한 보여주시면 좋을 것 같습니다.
/ 개발하다 보면 다른 포지션에 신경쓸 겨를이 좀 부족한 것도 사실이라,, ㅋㅋ 신경써야겠다는 마음 가짐만 있어도 충분할 듯 싶네요 👍
- 'a' 인식 어려움 => 이 부분은 재학습을 시키거나 데이터 증강을 시켜서 좀 더 개선해보아야 할 듯 싶습니다 (😭)
-  기록이 활발하게 이루어지고 있으니 관련해서도 얘기를 나누는 시간을 가지면 좋을 것 같네요 👍

**Comment by PracticeEveryday** [comment]
T
 - 서비스에 대한 최종 목표를 스크럼 시작 때마다 상기시키기
 - 컨디션이 안 좋다면 이모지 Ex) 😨를 활용하여 스크럼 docs에 남기고 다음날 컨디션 관리를 할 수 있게 하는 것은 어떨까
 - => 찾지 않기

**Comment by Malza0408** [comment]
[T]
- 프론트에서 개선한 점이 있다면 오후 스크럼 때 바로 공유 가능하다. 또는 이슈에 남긴다.
- 개선점을 가지고 많은 의견을 주면 좋다.

**Comment by blcklamb** [comment]
### 최종 TRY

- 포지션 간 진행 상황 공유를 위해 타 포지션, 팀원이 오류 및 진행상황에 대해서 꼼꼼히 작성을 했다면, 해당 이슈를 읽었는지 확인하는 반응/댓글을 남기자.

- 1주일에 한 번은 코드를 정리하는 시간이 있으면 좋을 것 같습니다.

- 컨디션이 안 좋다면 이모지 Ex) 😨를 활용하여 스크럼 docs에 남기고 다음날 컨디션 관리를 할 수 있게 하는 것은 어떨까
=> 찾지 않기

**Comment by blcklamb** [comment]
this is temp message
